### ISSUE TITLE
cpu usage really high after reboot

### ISSUE THREAD

**Issue by davereiner** [lxc/lxcfs#114]
We had to do an emergency reboot on one of our machines and ever since it's rebooted LXCFS's CPU usage is really high. I'm curious why because prior to the reboot the number of containers and the running containers were exactly the same:
![LXCFS](http://i.imgur.com/UUzxgXx.png)

Logs of the LXCFS process only:
![LXCFS](http://i.imgur.com/FkdDQXG.png)

I'm not sure if it's related but since then file operations have been extremely slow, installing a single apt package can take up to 5 minutes (!) both in containers and on the host machine.
Host machine is Ubuntu 15.10 running the latest version of LXCFS.

1) Can I restart the LXCFS service on the host machine to see if that helps or will it break containers?
2) I can provide all the data necessary, just let me know how I can help.

Thanks!

**Comment by hallyn** [comment]
Hi,

To restart lxcfs without breaking containers, send it the SIGUSR1 signal.  If
a task is keeping an fd open (and abusing it) then this won't help since lxcfs
will wait until there are no active requests before reloading its liblxcfs
library.

You should be able to figure out what's going on by looking at a few things -

Which thread(s) is(are) active?  strace those and see what they are
doing.  Look at /proc/tid/fd/* to see what files they have open.

Look at lsof output for any /var/lib/lxcfs/ files, and investigate what
the tasks which have those open are doing.

**Comment by davereiner** [comment]
Couldn't figure this out so far, looks like it's the main LXCFS thread and going through the listed points I got nowhere. We're moving everything to a Xenial based server anyway, if this pops up again I will definitely dig deeper. Thanks for the quick reply!
