### ISSUE TITLE
Use already mounted cgroups

### ISSUE THREAD

**Issue by alehaa** [lxc/lxcfs#123]
As far as I known from inspecting the code, lxcfs mounts all cgroups at ``/run/lxcfs/controllers``, even if the cgroups are already mounted at ``/sys/fs/cgroup``. Libvirt doesn't like this at my server (Debian jessie), and I don't understand why this is necessary.

So I checked to use the cgroups under ``/sys/fs/cgroup``:
```diff
diff --git a/bindings.c b/bindings.c
index 8186ca9..a351b9a 100644
--- a/bindings.c
+++ b/bindings.c
@@ -762,9 +762,9 @@ bool cgfs_get_value(const char *controller, const char *cgroup, const char *file
        if (!tmpc)
                return false;
        /* basedir / tmpc / cgroup / file \0 */
-       len = strlen(basedir) + strlen(tmpc) + strlen(cgroup) + strlen(file) + 4;
+       len = strlen("/sys/fs/cgroup") + strlen(tmpc) + strlen(cgroup) + strlen(file) + 4;
        fnam = alloca(len);
-       snprintf(fnam, len, "%s/%s/%s/%s", basedir, tmpc, cgroup, file);
+       snprintf(fnam, len, "%s/%s/%s/%s", "/sys/fs/cgroup", tmpc, cgroup, file);
 
        *value = slurp_file(fnam);
        return *value != NULL;
```
This gave me no errors inside the container or at the console by lxcfs. Even better: if I unmount the ones under /run/lxcfs, libvirt will be happy, too.

I'd like to know, if a patch for detecting already mounted cgroups is welcome, of if this is a scenario that should not be used by lxcfs.

**Comment by brauner** [comment]
Unfortunately, we cannot unconditionally disable the cgroup mounts that `lxcfs` does under `/run/lxcfs/controllers`. `lxcfs` uses the mounts under `/run/lxcfs/controllers` to e.g. allow for things like only providing a partial view of the cgroup hierarchy. This is at least the case on systems with a kernel that does not support cgroup namespaces. Furthermore, on non cgroup namespace supporting kernels the cgroup part of `lxcfs` is needed to run systemd based containers. There was however, discussion of adding an option to `configure` to disable the cgroup part so that we can take it out on cgroup namespace enabled kernels.

**Comment by alehaa** [comment]
Okay I understand. Can this be checked in any way? Then I would spend some work on this ...

My intention was to check the mount table for already mounted cgroups that match the requirements of lxcfs (?) and skip those for mounting in ``/run``.

**Comment by hallyn** [comment]
Note the other thing we can do is to follow cgmanager's example and mount
those filesystems privately, so that libvirt won't see them.  The reason I
didn't do that here is because doing it without downsides requires setting
up our own tiny-chroot at startup - so that we don't pin any filesystems
which init might at some point want to umount.  We finally got it right in
cgmanager, but it was a bit painful and delicate.

**Comment by alehaa** [comment]
As a temporary fix I did this the other way around and told libvirt to ignore cgroup mounts mounted under ``/run/lxcfs``, but as libvirt is (in my opinion) a complex software, I don't like to patch something in it's code and would love to fix this in the more simple lxcfs ;)

**Comment by brauner** [comment]
To put `/run/lxcfs/controllers` into it's own tiny chroot seems doable. After unsharing our mount ns and remounting root as `MS_PRIVATE` we would unmount every fs we don't need and mount `/proc`, `/run`, `/dev` (because of `fuse`), `/sys` and `/sys/fs/fuse/connections` (`fuse` again (I assume we'd need this.)). That would cause `lxcfs` to be started in a private mount ns. The only thing that I don't have a solution for right now is how to actually have the container find the private mounts and be able to mount them in its own namespaces. Mostly, because our current `lxcfs` `lxc.mount.hook` assumes that the mounts under `/run/lxcfs/controllers/*` and `/var/lib/lxcfs/*` are visible in the host mount ns.

**Comment by hallyn** [comment]
This has been addressed by brauner iiuc - thanks.
