### ISSUE TITLE
loadavg and swap

### ISSUE THREAD

**Issue by devonblzx** [lxc/lxcfs#13]
Two additional files that should be considered for lxcfs:

/proc/loadavg
/proc/swaps

Both should be relatively easy to generate using cgroups and the existing information in lxcfs.
# cat /proc/loadavg

0.00 0.01 0.05 1/273 16306

loadavg consists of 1 minute average, 5 minute average, 10 minute average, running processes / total processes, last PID running

My idea was to poll the system every second and keep a database of the last 600 polls (10 minutes) consisting of the number of running processes.  This would allow you to generate averages as needed.
# cat /proc/swaps

Filename                                Type            Size    Used    Priority
/dev/sdb1                               partition       12582908        49188   -1

I'd assume you can generate a fake partition entry with integer values from cgroup/memory.

The size would be:
(memory.memsw.limit_in_bytes - memory.limit_in_bytes) / 1024

The usage can be derived from the 'swap' row in memory.stat divided by 1024 (since /proc/swaps reports in KB)

I'm not a C programmer so I can't assist with the code, but I'd be happy to help in ways that I can.

**Comment by richardland** [comment]
Would this also fix the issue that you see the CPU cores beeing busy in htop although the PID that cause the load on the CPU are not from the container where htop runs (ie; i have a container that does NOTHING but still sees a lot of load on the CPU)? Than this would be the most awesome feature; it would make LXC much more like a true hypervisor (as stated as a goal of LXD).

Even without this, this proposed fix for loadavg and the amount of available SWAP would be a great contribution. We are willing to help with this! Maybe devide the work that has to be done?

**Comment by tssge** [comment]
I have implemented /proc/swaps. Please see commit https://github.com/tssge/lxcfs/commit/50b75e323021a3d021711bc6adbbf9ec3b92847b for more information.

It needs testing, I haven't even tried compiling yet, but it should work. Maybe someone else would like to test it? Maybe @devonblzx ?

**Comment by richardland** [comment]
Great job! Stupid question probably, but whats the best way of testing this branch? I'm using ubuntu 15.04.

**Comment by tssge** [comment]
I think the best way is to just clone my branch, then follow the compilation instructions of lxcfs. Basically just clone my branch, make and make install and it should be up and running.

**Comment by richardland** [comment]
Thanks. I tried and get stuck here while doing the ./configure script (according to https://linuxcontainers.org/lxcfs/getting-started/ while using your fork)

checking for main in -lpthread... yes
./configure: line 12341: syntax error near unexpected token `GLIB,'
./configure: line 12341: `PKG_CHECK_MODULES(GLIB, glib-2.0)'

Tried installing every glib/dev/ package available but to no avail:

apt-get install make automake gcc autotools-dev libtool libglib2.0-dev intltool

Any ideas?

**Comment by tssge** [comment]
I'll work on the code, it is quite broken actually (I tested it). I was able to compile it however, using the instructions, not sure how to help with that.

**Comment by kartoffelheinz** [comment]
Any progress on the loadavg-feature? 

I would say swapping in general has become kinda obsolete anyway since memory is dirt cheap and swapping has too much of a performance malus anyway. 

But seeing correct loadavg is needed for proper monitoring guests to see "whats wrong where" if the host behaves unusually. Not even lxc-info will get me these numbers for guests at this moment.

So I would love to see support for guest-specific loadavg  implemented soon :)

**Comment by richardland** [comment]
I don' t know of any progress although it is a very important feature IMHO (especially the loadavg).

Swapping would also be nice because sometimes it simply is needed and clients do expect to have it. A nice solution would be to place swapspace on a seperate SSD to prevent system impact and to use block I/O cgroup to make sure everybody gets its share. Or in a less ideal (non seperate swapdrive) system; cap the usage of swap altogether to prevent extreme system slowdown. This is relatively simple with cgroups i guess. But still, without a way to see per container the swapusage, it would not really add value and we cannot monitor in a good way.

**Comment by tssge** [comment]
I have already implemented swap usage counting on htop and top, please see commit https://github.com/lxc/lxcfs/commit/4622ad783bb1252215666d9cf8b5149d7db3190b

This however does not mean that /proc/swaps works, but that is only used for things like swapon etc. I have implemented that as well, but not perfected.

Also, I have no idea how to implement load average. In my honest opinion it needs kernel support. I could program that as well, but I saw some older patches which were not liked and actually that led to creating lxcfs I think so yeah... hard problem.

**Comment by richardland** [comment]
@tssge Good work! Thanks. I see that it is not in any distribution yet, thats why i didn't see it. I'll give it a try using https://linuxcontainers.org/lxcfs/getting-started/

For the loadavg, would we need some sort of /proc/stat emulation?? I really wonder how Canonical is planning to do this. Without loadavg it is simply not workable if you plan on giving clients full server access. They would not know how heavy their VPS is used. Although through /sys/fs/cgroup/cpu/lxc/my-container/cpuacct.usage and such we could make a webbased overview for them.

I tried https://linuxcontainers.org/lxd/try-it/ to see if LXD somehow got around this, but is doesn't seem so. Although i must say the demo with nested containers is cool!

**Comment by nehaljwani** [comment]
I have worked upon tssge@50b75e3 and fixed the issue when memsw limit is not specified. It passes minimal testing from my side. I am not sending a pull request since it isn't completely my work. It is available at: https://github.com/nehaljwani/lxcfs/commit/d99008439565e95f0b19524c97d717ed3b0c26ba

**Comment by hallyn** [comment]
Hi,

"not completely your work" is not a problem, this is open source :)
The main problem is the original patch is not signed-off;  I would
recommend pinging him asking for a SOB, then put that above your
own in your patch and send the PR.

**Comment by nehaljwani** [comment]
@hallyn I had sent my patch to the mailing list. What's SOB?

**Comment by tssge** [comment]
Can I just inform here that I hereby sign off my patches for inclusion to lxcfs? The patches are found here with commit id's dae4bb1cf6f7175e48c156c6035048f3f6e1519b, 50b75e323021a3d021711bc6adbbf9ec3b92847b and 1aabdda1015abc9e1f48f367cbb93984c5202457.

The patches are hereby signed off by Teemu Grönqvist <teemu.gronqvist@net9.fi>.

I guess I could rewrite history as well but yeah.

**Comment by tssge** [comment]
What patches are you talking about? Am I missing something? Something I should sign?

I can sign, just tell what.

**Comment by nehaljwani** [comment]
@tssge Could you please rework on the comment at https://lists.linuxcontainers.org/pipermail/lxc-devel/2016-January/013326.html and send it again with a Signed-off-By?

**Comment by tssge** [comment]
I signed it off and sent to the mailing list.

**Comment by hallyn** [comment]
Thanks,

@nehaljwani, are you willing to take that and push a new PR against the current lxfs source?

**Comment by nehaljwani** [comment]
@hallyn I was just about to send the PR, when I saw 70dcc12e30eede95de6a4145bcbebd87aa6c3eeb. Missed by by an hour :)

**Comment by hallyn** [comment]
On Tue, Feb 09, 2016 at 12:52:51PM -0800, Nehal J Wani wrote:
> @hallyn I was just about to send the PR, when I saw 70dcc12e30eede95de6a4145bcbebd87aa6c3eeb. Missed by by an hour :)

Oh, sorry.  Please do double-check that I didn't get anything wrong.
(I fixed a fd and memory leak inline as well)

**Comment by tssge** [comment]
Now that swaps seems to be merged, any idea on how the loadavg should be done? I don't know where to start really.

**Comment by hallyn** [comment]
On Tue, Feb 09, 2016 at 09:55:39PM -0800, Teemu Grönqvist wrote:
> Now that swaps seems to be merged, any idea on how the loadavg should be done? I don't know where to start really.

I've heard no good ideas so far.

**Comment by kartoffelheinz** [comment]
Disclaimer: I have no real experience hacking lxc / kernel stuff.

As far as I understand, load average is (i simplify) calculated using the count of processes that wait  on I/O and how long they do so. It actually is quite simple to calculate, if I believe https://en.wikipedia.org/wiki/Load_%28computing%29

Cant you just use that to calculate the same load average, but just for processes in the given lxc guest namespace and then overriding /proc/loadavg? The latter is the hard part I guess, but until we have a solution for that, we could just use /proc/loadavg_lxc or that kind. That way, actually could find the culprit guest that caused loadavg spikes on the host system (because we can monitor /proc/loadavg_lxc inside guests) which is currently next to impossible after the fact.

**Comment by devonblzx** [comment]
Re: loadavg

I haven't really been involved with this thread much since I opened it about a year ago, but the only idea I could think of is constant polling with some sort of database, as suggested in the OP.  The load average only needs to consist of the last 600 seconds (10 minutes), so depending on the poll frequency, we can generate a pretty good estimate by storing the number of running processes in the container and generating an average of the polls from the last 60 seconds, 300 seconds, and 600 seconds everytime loadavg is read inside the container.

I don't have a system in front of me at the moment, but is there a cgroup param for processes in a running or i/o wait state?

The problem with this solution, of course being that if you have lots of containers, there is a lot of polling going on, but without constant polling, I don't see of a way to find out how many running processes there were x seconds ago to generate an average.

**Comment by hallyn** [comment]
Right, that is exactly the problem.

Our two main options seem to be to (1) propose a cgroup extention (maybe
to cpuacct or to pids cgroup) which tracks this information, or (2) track
the info in userspace, running a thread every 5 seconds to collect data,
and storing it in a file in case lxcfs gets restarted.  I believe it
would need to go through the thousands of /proc/pid/status files to 
determine which tasks are running or in uninterruptible sleep.

**Comment by tssge** [comment]
What about kernel support? I myself have done some kernel code before and might be able to rip this off of OpenVZ. Any idea if they'd like a patch that counts cgroup loadavg in the kernel?

**Comment by hallyn** [comment]
Quoting Teemu Grönqvist (notifications@github.com):
> What about kernel support? I myself have done some kernel code before and might be able to rip this off of OpenVZ. Any idea if they'd like a patch that counts cgroup loadavg in the kernel?

Since there is effectively no good cheap way to do it in userspace, it may be doable.

I'd encourage you to proceed :)

Thanks!

**Comment by jcarnus** [comment]
Hi, what is the status of this feature ?

**Comment by TheNuclearCat** [comment]
Would also know if someone is working on it?

**Comment by hallyn** [comment]
@TheNuclearCat - not that I know of.  Are you considering it?

**Comment by TheNuclearCat** [comment]
@hallyn I would, but unfortunately I have not enough knowledge yet :)

**Comment by Harvie** [comment]
This is issue as our clients have 1-2 CPU containers on our 48 CPU server. On such server it's perfectly OK to have loadavg of 30 (because it's lower than processor core count), but it looks really bad in 1 or 2 CPU container, which might make clients doubt about quality of our service... For example on OpenVZ they calculate loadavg individualy for each container, which looks much better and is even useful.

**Comment by stgraber** [comment]
We know the reason for wanting this, we just need someone to find a way to implement the logic needed in lxcfs :)

**Comment by tomponline** [comment]
Is this something that Docket/RKT has overcome, or do they share the same issue because of the underlying use of cgroups/namespaces?

**Comment by Harvie** [comment]
@stgraber is it possible to partialy reuse OpenVZ code? It should be GPL as it's part of kernel.

**Comment by hallyn** [comment]
Quoting TomP (notifications@github.com):
> Is this something that Docket/RKT has overcome, or do they share the same issue because of the underlying use of cgroups/namespaces?

As far as I know they have the same problem.  They reimplemented (a
subset of) lxcfs in go and use that.  Last I checked they did not
overmount loadavg.

In a few weeks I may have some time to look at this - though I have a
menu of options to choose from for things to work on :) , so if it is
important enough to you for you to find time to work on it, please don't
wait for me.  I'll be happy to help any way I can.

-serge

**Comment by hinhthoi** [comment]
I'm also looking forward for this problem to be fixed. It is important that the statistics (cpu info, ram, swap, average load) should be isolated for each containers, so that it doesn't confuse users

**Comment by Harvie** [comment]
@hallyn Hey, but openvz has this implemeted. Would it be hard to port from openvz to lxc?

**Comment by stgraber** [comment]
@Harvie the logic could be re-used, but the fact is that OpenVZ was doing all this at the kernel level where all the needed information is available. It's been made clear multiple times that the upstream kernel community doesn't want the files in /proc as exposed by the kernel to reflect container limits.

So the difficulty we have now is that we need to do this in lxcfs which is a userspace program (fuse filesystem) which can only see what's available to userspace. This makes it very expensive to iterate through big set of process information because that may mean opening hundreds or thousands of files (one or more per process), then parsing all of them and doing math on top of it to come up with the load number.

It's certainly not impossible, but we have to find a reasonably cheap way of doing it because having to constantly poll the process list of every container and do math on the process scheduled time is going to cause a much bigger load on your system than the container itself does :)

**Comment by Harvie** [comment]
@stgraber they don't want to change behaviour of /proc/loadavg or they don't want to expose it at all?
Like they have some reasons not to add per cgroup statistics to completely new files like `/proc/cgroup/lxc/214/ns/stats` ? Is there some good reason not to have this in kernel? Is it possible to solve this problem easily using kernel module?

**Comment by hallyn** [comment]
New files under /proc are heavily frowned upon.

Actually what *might* be doable is a new cgroup subsystem, which just tracks the load for each cgroup.

I'm also not sure whether anyone has ever considered just adding a "cgroup.loadavg" type file, allowing the kernel to give us the info for any cgroup (and its descendents).

I think *that* might be the best place to start here.

**Comment by brauner** [comment]
On Tue, Dec 05, 2017 at 03:33:42PM +0000, Serge Hallyn wrote:
> New files under /proc are heavily frowned upon.
> 
> Actually what *might* be doable is a new cgroup subsystem, which just tracks the load for each cgroup.
> 
> I'm also not sure whether anyone has ever considered just adding a "cgroup.loadavg" type file, allowing the kernel to give us the info for any cgroup (and its descendents).
> 

So that would be a new file per each cgroup? Hm...
For cgroup v2 it would be easier to just add an entry to the newly
implemented "cgroup.stat" (
https://www.kernel.org/doc/Documentation/cgroup-v2.txt )file. For cgroup
v1 it's questionable whether new files would still be accepted, right?

**Comment by hallyn** [comment]
Quoting Christian Brauner (notifications@github.com):
> So that would be a new file per each cgroup? Hm...
> For cgroup v2 it would be easier to just add an entry to the newly
> implemented "cgroup.stat" (
> https://www.kernel.org/doc/Documentation/cgroup-v2.txt )file. For cgroup

Sounds good to me.

> v1 it's questionable whether new files would still be accepted, right?

Yeah, true.

**Comment by amostech** [comment]
Hi guys. Is the an update on how to proceed with this? I've seen comments regarding this issue in other places as well but they pointed to this issue. Is there any workaround for this in the meantime, maybe installing some package in the containers.

**Comment by devonblzx** [comment]
@amostech Not erroneous, just the difference between a container and virtual machine.  LXCFS tries to emulate various counters but if you read through this thread, you'll see there is no efficient way to calculate load numbers for containers at this time.

**Comment by richardland** [comment]
My conclusion after using containers for a decade is that containers (docker,lxc, openvz etc) are simply not a "true"-VM. It is an amazing technology for developing and offering a SAAS product though! Unbeatable in CPU and MEM efficiency and ease of deployment. And within a SAAS solution these problems discussed here are far less problematic and cgroups should give perfect way of isolating things. 

So IMHO containers not suitable for true VM "hosting". When clients expect a actual VM, always go for KVM/Xen/VMware. 

And don't forget that all containers have the problem of missing sys_rawio permisison in kernel because of security (you can enable this, but at a serious security cost). This means that the max IOPS generally are about 1000 (HDD speed). Maybe with a good CPU you can boost this to maybe 10.000 by wasting CPU time on checking permissions. But you will never get 100.000 (SSD) - 400.000 (NVME PCIe) with low CPU directly via the controller. Only solution is probably integrating the (Intel VT or AMD-V) features. 

This in mind, maybe it is not very useful to try to go to deep in something that is not going to work anyway. Maybe just accept the downfalls and enjoy the good sides as well and use accordingly.

**Comment by richardland** [comment]
You are right. Sorry for the bad info. This was only for privileged old containers as it seems  (https://www.nccgroup.trust/globalassets/our-research/us/whitepapers/2016/june/container_whitepaper.pdf). Still strange that CAP_SYS_RAWIO is disabled on OpenVZ and that it causes low IOPS. But this is probably not the place to discuss this.

**Comment by Harvie** [comment]
in htop i see some basic stats (CPU%, CPU time, etc..) for indivudal processes. you can take these numbers for all processes of lxc container sum them up and present them. Does not have to be really precise, still better than nothing. Eg.:

Host is running 20 containers and has loadavg of 10:

One of the containers has following processes:
```
apache 3% CPU
postfix 5% CPU
SUM 3+5 = 8% CPU
```
Loadavg shown in container can be host load * SUM of %CPU, which is 8% of 10 = loadavg of 0.8.

This is not very accurate, but the output would make much more sense to the customers who don't have any idea about activity in 19 other containers. (They will not see load while not having any processes running).

With some modifications you would be able to apply this calculation to calculate % load of single CPU core, but you have to calculate it just from the processes running on that core (that's different from loadavg, which is global for all cores).

**Comment by brauner** [comment]
The  loadavg part is implemented and opt-in now.

**Comment by Harvie** [comment]
@brauner cool! which commit?

**Comment by brauner** [comment]
https://github.com/lxc/lxcfs/pull/237 :)

**Comment by PowerMakc** [comment]
Excuse me, how do I get loadavg support? I have the latest version of lxcfs from the official repository ubuntu 18.04.1, but it does not have loadavg

**Comment by zerkms** [comment]
@PowerMakc how do you run your `lxcfs`? https://github.com/lxc/lxcfs/pull/237 states you must specify the `-l` key specifically.

**Comment by PowerMakc** [comment]
I do not run it separately, I'm guided by the lxcfs description line - "use LXC 1.1 in which case it should work automatically". My version of LXC 3.0.1. Perhaps I'm mistaken that it should work automatically.

**Comment by zerkms** [comment]
> Perhaps I'm mistaken that it should work automatically.

That phrase means lxc supports systemd-based containers starting v1.1

**Comment by zerkms** [comment]
What `lxcfs` version are you running?

**Comment by PowerMakc** [comment]
lxcfs --version
3.0.1

**Comment by PowerMakc** [comment]
I do not understand :) I used this https://linuxcontainers.org/lxcfs/getting-started/#building-and-running-lxcfs-from-git, downloaded the git version, compiled and **./lxcfs --version** shows me **3.0.0** and in output lxcfs -h is "**-l use loadavg**", but now I have **3.0.1**, which was installed with LXC and in lxcfs -h there is **no** "-l use loadavg". 
Maybe this is due to the recent update from 16.04 to 18.04.1? 
If I try to run git version 3.0.0 
`sudo ./lxcfs -s -f -o -l allow_other /var/lib/lxcfs/` 
then I get
`lxcfs.c: 84: start_loadavg: load_daemon fails: /usr/local/lib/lxcfs/liblxcfs.so: undefined symbol: load_daemon`

**Comment by Harvie** [comment]
Because 3.0.0 from git is not the same as 3.0.0 release.

**Comment by PowerMakc** [comment]
I need to delete the standard lxcfs and use the only git version?
How to fix **lxcfs.c: 84: start_loadavg: load_daemon fails: /usr/local/lib/lxcfs/liblxcfs.so: undefined symbol: load_daemon**?

**Comment by Harvie** [comment]
This has been merged downstream to Proxmox VE. See this thread on how to enable it:
https://forum.proxmox.com/threads/lxc-loadavg.44463/

**Comment by loxK** [comment]
I am running 3.18 from snap and lxcf does not show the -l parameter ? What am I doing wrong ?

```
$ lxd --version
3.18
$ lxcfs -h
Usage:

lxcfs [-f|-d] [-p pidfile] mountpoint
  -f running foreground by default; -d enable debug output 
  Default pidfile is /run/lxcfs.pid
lxcfs -h

```

**Comment by hallyn** [comment]
On Mon, Jan 20, 2020 at 08:47:55PM -0800, Laurent Dinclaux wrote:
> I am running 3.18 from snap and lxcf does not show the -l parameter ? What am I doing wrong ?
> 
> ```
> $ lxd --version

Note lxcfs and lxd are not tied.  You'd need to do lxcfs --version

> 3.18
> $ lxcfs -h
> Usage:
> 
> lxcfs [-f|-d] [-p pidfile] mountpoint
>   -f running foreground by default; -d enable debug output 
>   Default pidfile is /run/lxcfs.pid
> lxcfs -h

so the -l option was added in master in May 2018 (commit 6db4f7a3),
but it was never added to the stable-3.0 branch, which I am running,
and you probably too.
