### ISSUE TITLE
Block access to /dev/kmsg

### ISSUE THREAD

**Issue by tssge** [lxc/lxcfs#131]
As described here https://bugzilla.proxmox.com/show_bug.cgi?id=839#c9 containers can see host's /dev/kmsg. Should lxcfs just block access to the real /dev/kmsg by returning nothing when that file is read? This is what OpenVZ does (I think), so it would be quite reasonable for lxcfs to do the same thing.

Suggestions?

**Comment by stgraber** [comment]
So this bug should be filed against LXC if anywhere.

Though the default LXC policy doesn't allow any kind of access to /dev/kmsg so if you're actually able to read and write to it, it's most likely through misconfiguration on your end rather than a LXC problem.

Note however that /dev/kmsg isn't the only way to read the kernel log, very far from it. This can also be done through /proc or through a syscall. Blocking all of those will make some software crash in the container so we don't do that by default. You are obviously free to write your own policies and block that if you want.

In unprivileged containers, you can set /proc/sys/kernel/dmesg_restrict so that only real root can read dmesg, preventing even root inside the container from accessing it. Again, this is likely to cause a bunch of crashes, especially from monitoring systems.
