### ISSUE TITLE
Support running on initramfs

### ISSUE THREAD

**Issue by thinxer** [lxc/lxcfs#144]
When the system root is on initramfs, `pivot_root` doesn't work and LXCFS fails.

```
pivot_enter: pivot_root() syscall failed: Invalid argument.
```

Docker solves this by providing a `DOCKER_RAMDISK` flag. When set, Docker uses `chroot` instead of `pivot_root`.  Is this possible with lxcfs?

**Comment by brauner** [comment]
That should be doable, yes.

**Comment by stgraber** [comment]
If I remember the kernel code properly, the problem is that you can't pivot_root when your new path is a ramfs. So instead of using env variables, we could probably just statvfs the new root and if it's a ramfs, then use chroot.

Or you could do what I was doing on Android which is to setup a tmpfs, then bind-mount the paths I care about, then pivot_root to that as pivoting to a tmpfs is perfectly fine. The use of the tmpfs can then be made conditional on / being a ramfs.

**Comment by brauner** [comment]
The first option is similar to what we do in `LXC` but for `LXCFS` the second option might make more sense.

**Comment by brauner** [comment]
@hallyn, this can be closed.
