### ISSUE TITLE
fusermount: failed to unmount /var/lib/lxcfs: Invalid argument

### ISSUE THREAD

**Issue by MarkGavalda** [lxc/lxcfs#146]
Ubuntu 16.04
kernel: 4.4.0-36-generic
LXCFS 2.0.3

```
$ systemctl stop lxcfs
Sep 12 11:50:39 lxd-9 fusermount[15162]: /bin/fusermount: failed to unmount /var/lib/lxcfs: Invalid argument
```

Confirmed with _mount_ that everything is still mounted.

**Comment by stgraber** [comment]
Yeah, that's normal behavior for the systemd unit, not a lxcfs bug.

systemd always runs a fusermount call on exit of lxcfs just in case lxcfs crashed instead of properly exitting and the filesystem is still mounted.

The fusermount failure if it's already unmounted is ignored (prefixed with - in the systemd unit).
