### ISSUE TITLE
CPU usage is shared among VMs

### ISSUE THREAD

**Issue by servereasy-saverio** [lxc/lxcfs#180]
Hi,

Inside the VMs, _top_ shows the CPU usage of the whole node.

**Comment by hallyn** [comment]
Do you have your containers configured to isolate cpus or cpushare?  Can you show your container configuration and precisely which fields are not being properly virtualized?

**Comment by servereasy** [comment]
cpushare:

...
limits.cpu: "8"
...

For example, if inside "VM A" I produce 100% CPU usage, inside "VM B" I see 100% CPU usage (if the assigned cores are the same, of course)

**Comment by kovanorby** [comment]
Hello!

I'm usign proxmox, but on the lxc vps i only see the load of the physical cpus... It's not good this way

**Comment by hallyn** [comment]
If the containers are sharing cpus then indeed they will see each others' loads.

If someone would like to work an a good solution to this, please feel free (and post here your plans and progress and questions) - we'll leave this issue open to track that.  If I find some time to work on it I'll do so.

As a workaround you can dedicate cpus to specific containers.  Of course that's sub-optimal if you have 4 cpus and 1k containers.

**Comment by servereasy-saverio** [comment]
Hello,

Is there any plan about this?

**Comment by aither64** [comment]
I've tried to implement this feature, but I'm not sure if there is actually a way to do this properly without the kernel providing more information. I've made it so that LXCFS reads CPU usage from the container's cpuacct cgroup and then uses those values to override `/proc/stat` given to the container. The issue is that the cgroup is accounting only usage in `user` and `system` modes. I was able to calculate idle time based on values from `/proc/stat`, but it may not be very accurate, because accounted usage by `/proc/stat` and the cgroup differs a bit... I've no idea what to do about other fields in `/proc/stat`, like `nice`, `iowait` or interrupts, so those fields are always set to `0`. Here's the patch: https://github.com/aither64/lxcfs/tree/independent_cpu_usage

@hallyn, what do you think about it, is there a better way?

**Comment by N-Storm** [comment]
Maybe take a look at OpenVZ code? This was implemented there for ages. As for LXC this issue was raised so many times for years but nobody cares. Like #40 was closed without any comments.

**Comment by hallyn** [comment]
@N-Storm as we said, this requires kernel support.  That's how OpenVZ did it.  lxc aims to work purely with upstream kernel (or at least patches on their way upstream).

This feature honestly is not important to me (I have no use for it) so I'm unlikely to work on it in my spare time.  I'll definitely review and integrate community work on it, which is why the issue is still open.

**Comment by stgraber** [comment]
So we have the /proc/stat virtualization now which is as close to this as we can get without kernel changes, considering this done on our side then.
