### ISSUE TITLE
when lxcfs receive signal kill, we should umount the mount path(eg: /usr/local/var/lib/lxcfs/)

### ISSUE THREAD

**Issue by y123456yz** [lxc/lxcfs#204]
if we don't do this, we should umount the path manually, it is inconvenient

**Comment by brauner** [comment]
`SIGKILL`? That won't work you can't handle this signal.

**Comment by y123456yz** [comment]
@brauner 
In my test, I kill lxcfs and then restart it.

brauner, in my environment， I find another serious problem:
I go into lxc-container through lxc-attach,  then I cat /proc/cpuinfo: Transport endpoint is not connected 

 I back to the physical host,  I see that the lxcfs process is runing, not hung.


my lxcfs version:2.0.0
$ /usr/local/bin/lxcfs --version
2.0.0

I use libfuse-fuse_2_9_2

thanks, brauner.
can you give a few suggestions to me. 
thanks again.

**Comment by brauner** [comment]
@y123456yz you should never kill `lxcfs` via `SIGKILL`. `SIGKILL` cannot be handled by a program instead it will simply terminate without performing any cleanup operations. However, if you want to reload lxcfs you can do so very easily since it is implemented in such a way that it uses a fully-reloadable libtool module. To reload lxcfs without restarting it you just have to send `SIGUSR1` to the PID of `lxcfs`.

The `Transport endpoint is not connected` problem is caused by the fact that you have killed `lxcfs` which means the mountpoints inside the container that it sets up are invalid. There's no (real) way to recover from this but to restart the container. But as I said it is not necessary to kill `lxcfs` to restart it. Simply send `SIGUSR1` to the PID of `lxcfs`.

**Comment by y123456yz** [comment]
@brauner 
In my production environment, I do not kill lxcfs, I only kill lxcfs in my test environment.
bug the "Transport endpoint is not connected" is appeared in my production  environment.
I see that lxcfs is runnint(through "ps -ef | grep lxcfs").

In my product environment, I never kill or restart lxcfs.

@brauner 
look forward to your reply
thanks again.

**Comment by brauner** [comment]
- Do you see any interesting output in `dmesg` when this error happens?
- What does `systemctl status lxcfs` show on your production system?
- Did `lxcfs` ever crash on your production system? If so then this explains the message you're seeing and you should, if possible, reboot the container.

Btw, the version of `lxcfs` you're using is super-old. You should update if possible.

**Comment by y123456yz** [comment]
sorry, Time is too long, I have restart container one months ago.

@brauner 
where have the brief description of diffrent lxcfs release.
thanks
