### ISSUE TITLE
Wrong RAM usage report in htop / ubuntu 16.04

### ISSUE THREAD

**Issue by lug-gh** [lxc/lxcfs#222]
Hi, on containers with ubuntu 16.04 i get wrong ram usage in htop

lxc-ls --version
2.1.0

lxcfs --version
2.0.7

![yos](https://lickmynip.pl/share/i/6ny63orn77.png)

free -m
              total        used        free      shared  buff/cache   available
Mem:            512         204         292         956          14         292
Swap:             0           0           0

ram usage shown in proxmox: 142 mb

so everything shows different values, which one to trust?

**Comment by brauner** [comment]
This has been changed by @Blub and there's really not nice way to do this since memory info with cgroup v1 is not very nice.

**Comment by lug-gh** [comment]
Ehm I don't really understand what you're trying to tell me :(

**Comment by brauner** [comment]
Oh, I mixed your issue with another one it seems. Ok, so is this reproducible with current `LXCFS` aka `2.0.8` and `3.0.0`?

**Comment by lug-gh** [comment]
lxc-ls 3.0.0 and lxcfs 3.0.0

![free -m](https://lickmynip.pl/share/i/ojyi45a81p.png)
![htop](https://lickmynip.pl/share/i/eqzkqudpfa.png)

**Comment by aither64** [comment]
I've noticed wrong memory usage info in htop as well. In our case, the issue is that in `/proc/meminfo`, LXCFS is handling `Cached` and `SReclaimable`, but `Shmem` is passed as-is from the host. @lug-gh, do you have high `Shmem` in `/proc/meminfo` as well? It should be the difference between the reported memory usage in htop and free.

The way htop calculates memory usage is this (see [here](https://github.com/hishamhm/htop/blob/666e1e76b39ee66a38f5fb620d22b23f36859eca/linux/LinuxProcessList.c#L960) and [here](https://github.com/hishamhm/htop/blob/666e1e76b39ee66a38f5fb620d22b23f36859eca/linux/Platform.c#L203)):
```
cachedMem = Cached + SReclaimable - Shmem
usedMem = MemTotal - MemFree - Buffers - cachedMem
```
Since `Cached` is low, `SReclaimable` is always zero and `Shmem` is taken from the host and can get quite large, `cachedMem` becomes a negative number and actually increases `usedMem`.

For our usecase, I've [worked around it](https://github.com/aither64/lxcfs/commit/282d0916f4e4617fef4302487c8f2c8350693f33) simply by setting `Shmem` to zero. Perhaps `parse_memstat()` could be made to read `shmem` from `memory.stat` as well, but I've discovered that just now, so I'm not sure.

**Comment by lug-gh** [comment]
yes, Shmem is the problem. Subtracting Shmem from htop shows the real ram usage which is also shown in proxmox.

**Comment by brauner** [comment]
I think we have fixed this in master too. If not, please reopen.

**Comment by lug-gh** [comment]
tbh I completely lost track of this issue.

currently proxmox is using version 3.x so I'll have to wait, with this versions it's still a thing:

```lxc-ls --version```
3.2.1-devel
```lxcfs --version```
3.0.0
