### ISSUE TITLE
failed to execute mount: No such file or directory

### ISSUE THREAD

**Issue by bestkillua** [lxc/lxcfs#264]
1, commands

```
nsenter --target 37155 --mount -- mount -o /var/lib/lxc/lxcfs/proc/meminfo /proc/meminfo
```

If i use docker image of centos:7, it works. But if i use docker ubuntu:16.04, it occurs error 
```
failed to execute mount: No such file or directory
```

2, other information

```
docker version: 17.03.2-ce
kernel: 4.4.111-1.el7.elrepo.x86_64
```

**Comment by stgraber** [comment]
That command above is completely invalid, I don't know how this would ever work.

It should be `mount -o bind` and for this to work, both the source and destination paths need to exist (that's likely the source of the error).

lxcfs itself doesn't integrate directly with Docker, so the issue here most likely lies in whatever integration code you're using to make it work with Docker.
