### ISSUE TITLE
snap auto refresh lxd 3.15 kill lxcfs service

### ISSUE THREAD

**Issue by fungnaz** [lxc/lxcfs#295]
* Distribution: Ubuntu 
 * Distribution version: 16.04.4 LTS
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.4.0-116-generic
   * LXD version: snap 3.15 Rev: 11320
   * Storage backend in use: zfs

# Issue description
snap auto refresh to LXD 3.15 and found /proc incorrect behavior 

**on container**
root@envoy:~# free -m
Error: /proc must be mounted
  To mount /proc at boot you need an /etc/fstab line like:
      proc   /proc   proc    defaults
  In the meantime, run "mount proc /proc -t proc"

**on host**
when use ps fauxww | grep lxcfs
not found any service running 

**Fix**
on host
1. systemctl reload snap.lxd.daemon
2. restart container 

PS: after restart container I found mount proc boot_id, it's new on this release?
none /proc/sys/kernel/random/boot_id tmpfs ro,nosuid,nodev,noexec,relatime,size=492k,mode=755,uid=1000000,gid=1000000 0

**Comment by stgraber** [comment]
@fredt34 On the server where things didn't break, can you show me `journalctl -u snap.lxd.daemon -n 300`?

**Comment by fredt34** [comment]
After reloading lxd, we applied 3 methods with success to restore containers:
- reboot
- lxc restart
- umounting lxcfs mounts (```umount $(grep lxcfs /proc/mounts | cut -d " " -f2)``` is shorter)

**Comment by stgraber** [comment]
https://github.com/lxc/lxcfs/pull/296 should be the fix, but I'd like the confirm that your unaffected system is unaffected for the reason I think it is.

**Comment by fredt34** [comment]
@stgraber Here it is.
[journalctl-snap-lxd-daemon.log](https://github.com/lxc/lxcfs/files/3422759/journalctl-snap-lxd-daemon.log)

**Comment by stgraber** [comment]
Ok, looks like your lxcfs isn't reloading for some reason on that system, so that's likely what saved you.

**Comment by fredt34** [comment]
As Said Murphy : "Your Production Host Shall Not Be Saved, Only Your Useless Servers"

**Comment by stgraber** [comment]
Ok, we fully understand the issue now and have fixes coming to our users ASAP.

The issue will hit you if:
 - The version of the snap that `lxcfs` was originally started from is no longer present in `/snap`
 - You're upgrading from 3.0.4 to 3.1.1

There are actually two bugs here:
 - lxcfs 3.0.4 to 3.1.1 hits an uninitialized struct, causing a segfault only in the upgrade case
 - The snap will attempt to re-exec the old liblxcfs library rather than the new one when the old one is still available. This likely saved 90% of our users in this particular case but also means that we couldn't have done a quick rollout of a critical security fix as such a fix wouldn't have been loaded on refresh...

Both issues are now fixed in the packaging branch and we're just waiting for a new snap to build from that. We'll validate that both issues are properly fixed and then roll it out to stable users.

**Comment by stgraber** [comment]
Just validate a 3.0/candidate to latest/candidate upgrade, the snap picked up the right library and the library didn't segfault upon loading, so I think we're good. Just waiting for some other architectures to complete building and for automated CI to give this the go ahead but we're otherwise good to go.

**Comment by fredt34** [comment]
Perfect, we'll restore the automatic snap update... Fingers crossed. Thank you!

**Comment by stgraber** [comment]
The fix has now rolled out to stable.

**Comment by angristan** [comment]
Will any manual action be required from the affected users once the fix has been rolled out?

**Comment by stgraber** [comment]
Nope, the fix should cause lxcfs to re-appear on those systems where it crashed before.
All newly started containers will be fine. Existing containers will need to be restarted or have lxcfs unmounted inside them per prior instructions (there's nothing we can do to automatically re-bind a dead lxcfs, that's why it's meant to re-exec and not ever be restarted).

**Comment by seanfulton** [comment]
Stefan the real issue here is choosing to distribute a production system like this via SNAP. I understand the rationale behind the snap folks wanting to force upgrades--and that's good for them. But your decision to use snap to distribute something mission-critical like LXD makes the platform EXTREMELY unreliable. I've lost production containers THREE TIMES this year because of this snap auto-upgrade bullshit. If you can't find a way to stop these auto-refreshes, then I think this branch of LXD needs to move to YUM and/or APT. The versions that are the repositories are uselessly out of date, and this SNAP nonsense has got to stop.

**Comment by seanfulton** [comment]
You know that the issue of this bug would not be nearly as bad if all of your users were not automatically upgraded AGAINST THEIR WILL!

**Comment by stgraber** [comment]
@seanfulton following this incident we've introduced a per-release track that you can select and then upgrade every month to the next feature release. Users staying on old release obviously will not be supported but at least they get to choose when to upgrade to the next feature release.

Look at `snap info lxd` and you'll notice you can now use `--channel=3.15/stable` so that you won't auto-upgrade to 3.16 when it releases.


The snap distribution model is a double edge sword, yes, it's easier to break deployments but it's also significantly easier to fix them. This specific issue would not have been found in normal testing of the LXCFS deb package nor would it have been found in traditional staging environments.

So it would still have primarily hit production users when performing the update, but instead of managing a < 12 hours total time from first report of breakage to fix rolled out to all stable users, we'd have seen the reports come in slowly over the course of a week or two, then it would have taken another week or two for a fix to go through the entire SRU process and make it to all users (account for mirror delays and some people manually applying updates).
