### ISSUE TITLE
Show only the cpu of the container

### ISSUE THREAD

**Issue by alphaonex86** [lxc/lxcfs#40]
Hello,

As qemu emulation, is more logic to display cpu 100% idle if the current vm is idle, even if the other cpu is busy by other vm.
This do information leak, is not good for the confidentiality.

Cheers,

**Comment by hallyn** [comment]
I'm not sure we want to go this far in lxcfs.  This may be more appropriate for libresource (github.com/hallyn/libresource)

(I could be wrong.  Happy to look at patches in any case.)

**Comment by alphaonex86** [comment]
I need work with debian 6 unpatched top/htop, ...

**Comment by hallyn** [comment]
The goal of libresource is to become used by top/htop etc instead of direct reading of /proc.  lxcfs is a temporary workaround.

As I said, happy to look at patches, my main blocker is lack of time to think through what exactly you want (and whether implementing it would adversely affect any other cases).  If you prefer to give me an explanation of how you would calculate the cpu time (rather than a patch to do it), that might be enough to get me started.

**Comment by Profileo** [comment]
Hello Hallyn,

Let us jump in this conversation as we are facing the same issues alphaonex86 describes in this post.
Profileo is web agency and a hosting provider specialized in Prestashop based e-commerce websites. With over 14 years of experience in this field, we are the first Prestashop partner in the world as we currently host over 400 production websites.

We made the deliberate choice to go toward LXC as our main virtualization technology for our nearly 69 physical servers because we needed a flexible, hardware and OS independant technology that can evolve along with the Debian distribution. We tested VMware, KVM, vServer and Proxmox technologies in the past, all of which had a blocking issue for us.

We were happy running LXC as our hypervisor until one of our customer pointed out this major flaw in the VM isolation mechanism. Better than long speeches, let me give a graphical example of the problem we are facing.
Here is what a htop reveals, on the left hand side from the LXC VM, on the right hand side on the host :

![lxc_htops](https://cloud.githubusercontent.com/assets/10273935/10571459/aada23ec-763f-11e5-8293-69f7c40f77c9.png)

​
You can clearly see that the VM is not using any CPU/RAM at all, the process are sorted by CPU usage and peeks at 0.0% CPU/RAM. However htop shows one CPU #1 load at 96.7% because of a rsync task that runs at the host level, as you can see on the right side.

You can easily see what is the problem here. As hosting provider, we should be able to provide our customer with isolated environment. A root user logged into a VM should not be able to access any of this information. This kind of security leak can lead to major risks, as a very skilled system engineer could access other VM process or even host processes!

For instance, the /proc folder of the host is openly accessible from the VM and exposes all sensible information about what is running on the server and how it's configured.

To our opinion, the idea of letting the VM access to all raw information from the host then filter it inside the tools through patches is a dangerous path to follow.

Can you tell us if there is a plan to adapt the LXC technology to a more secured and isolated model such as VMware or qemu can offer? Correcting this through a Debian patch would not be a suitable solution for us as we are running different versions from Debian 6 to Debian 8 on our servers. Best would be a LXC patch.

Best regards,

Profileo Team

**Comment by Ravilr1981** [comment]
Hello Hallyn,

Let us jump in this conversation as we are facing the same issues alphaonex86 describes in this post.
We are a hosting provider with over 400 production websites running on our servers.

We made the deliberate choice to go toward LXC as our main virtualization technology for our nearly 69 physical servers because we needed a flexible, hardware and OS independant technology that can evolve along with the Debian distribution. We tested VMware, KVM, vServer and Proxmox technologies in the past, all of which had a blocking issue for us.

We were happy running LXC as our hypervisor until one of our customer pointed out this major flaw in the VM isolation mechanism. Better than long speeches, let me give a graphical example of the problem we are facing.
Here is what a htop reveals, on the left hand side from the LXC VM, on the right hand side on the host :

![lxc_htops](https://cloud.githubusercontent.com/assets/15191639/10572445/c5732196-7648-11e5-92ac-979f02ebe5cb.png)


​
You can clearly see that the VM is not using any CPU/RAM at all, the process are sorted by CPU usage and peeks at 0.0% CPU/RAM. However htop shows one CPU #1 load at 96.7% because of a rsync task that runs at the host level, as you can see on the right side.

You can easily see what is the problem here. As hosting provider, we should be able to provide our customer with isolated environment. A root user logged into a VM should not be able to access any of this information. This kind of security leak can lead to major risks, as a very skilled system engineer could access other VM process or even host processes!

For instance, the /proc folder of the host is openly accessible from the VM and exposes all sensible information about what is running on the server and how it's configured.

To our opinion, the idea of letting the VM access to all raw information from the host then filter it inside the tools through patches is a dangerous path to follow.

Can you tell us if there is a plan to adapt the LXC technology to a more secured and isolated model such as VMware or qemu can offer? Correcting this through a Debian patch would not be a suitable solution for us as we are running different versions from Debian 6 to Debian 8 on our servers. Best would be a LXC patch.

Best regards,

**Comment by box13100** [comment]
Hi,

You are right Ravilr1981. I have the same problem for my customers.
Without this isolation, I always have to explain to my customers why the CPU/load average is moving on their "empty environment".

Thank you for this comment and hope Hallyn will do some changes :)

Best regards from Barcelona

**Comment by hallyn** [comment]
Do you know offhand whether

https://github.com/lxc/lxcfs/issues/50

would address this?  I.e. is the idle time in /proc/uptime what is used by htop?  If /proc/pid/ info is used, then lxcfs cannot help (without incurring much higher performance penalty due to having to intercept every /proc/* open)

Note also that when I closed this issue, I said I'd be happy to look at patches.  This is an open source project, only one of several that I'm a part of.  I clearly have my own priorities for *development*;  for patch review/guidance/acceptance I mostly put my own priorities aside.

**Comment by hallyn** [comment]
Ok, looking at htop's source, i guess it uses /proc/loadavg.

**Comment by gucki** [comment]
This is still "broken" in ubuntu 16.04?

**Comment by alphaonex86** [comment]
Yes, still broken in ubuntu and other linux

**Comment by hallyn** [comment]
Reminder, the fix for this (iiuc) is blocked on issue #13

**Comment by amostech** [comment]
Same here in 2017. Has anyone found a way to overcome this? Even installing libresource or something similar would be considered OK for our use case. 

Basically I need top to show isolated resource usage instead of information from the host. 

If this has not been included in LXC then what are the correct ways to work around this? If there is a patch then could you guys point out the correct way to do this? We can patch the machines without no issues and include this in the base image for future LXC containers as well.

Best.
@hallyn

**Comment by N-Storm** [comment]
Why this was closed without any comments? This is still an issue in 2018. OpenVZ didn't had such problems for years. Comment at least please.

**Comment by angristan** [comment]
@hallyn It is not.

**Comment by jbenguira** [comment]
yes still an Issue in 2019 :(

**Comment by hallyn** [comment]
Please see https://github.com/lxc/lxcfs/pull/278  .
