### ISSUE TITLE
lxcfs is readonly?

### ISSUE THREAD

**Issue by yangdongsheng** [lxc/lxcfs#59]
Hi guys, does lxcfs simulate the whole /proc? I mean, example, can we provide the writable files, such as /proc/sys/kernel/core_pattern, for per-contianer via lxcfs??

**Comment by stgraber** [comment]
lxcfs only overrides individual files, it doesn't cover the entirety of proc as doing so would massively degrade container performance.

You could have lxfs define a /proc/sys/kernel/core_pattern hook, though there's not much you could do about it really. lxcfs itself is stateless so you'd need to store the value somewhere and then define some kind of wrapper in the real kernel-wide /proc/sys/kernel/core_pattern to call the right hook in the right container.

FWIW, it's something we've attempted in the past and lead to two CVEs and a lot of headaches. It's very difficult to figure out where to forward the crash and how to do it safely. Also, anything expensive on the host side can then be triggered by any container and cause a DoS.

Our current plan in Ubuntu is to revive my earlier implementation inside our crash manager (apport) and use a safe design instead of my earlier attempt:
https://bugs.launchpad.net/ubuntu/+source/apport/+bug/1445064

**Comment by yangdongsheng** [comment]
@stgraber Thanx. So I think the right way to achieve what I want it implementing a per-namespace core_pattern in kernel. Thanx for your information. :)
