### ISSUE TITLE
debian12 and ubuntu22.10 htop show wrong cpu

### ISSUE THREAD

**Issue by calvin2021y** [lxc/lxcfs#623]
```sh
podman run -it --rm -m 256m --memory-swap 256m  --cpuset-cpus=0-3 --hostname=test1  \
      -v /var/lib/lxcfs/proc/cpuinfo:/proc/cpuinfo:rw \
      -v /var/lib/lxcfs/proc/diskstats:/proc/diskstats:rw \
      -v /var/lib/lxcfs/proc/meminfo:/proc/meminfo:rw \
      -v /var/lib/lxcfs/proc/stat:/proc/stat:rw \
      -v /var/lib/lxcfs/proc/swaps:/proc/swaps:rw \
      -v /var/lib/lxcfs/proc/uptime:/proc/uptime:rw \
      -v /var/lib/lxcfs/proc/slabinfo:/proc/slabinfo:rw \
      -v /var/lib/lxcfs/sys/devices/system/cpu:/sys/devices/system/cpu:rw \
   debian:bookworm bash

cat /sys/fs/cgroup/cpuset.cpus
0-3
apt update
apt install htop
htop
```
change image ` debian:bookworm` into `ubuntu:23.10` get same results.

`ubuntu:23.04` show correct cpus with htop.

**Comment by stgraber** [comment]
Some newer software now uses the sysinfo system call rather than the filesystem as a way to get that information.

When that's the case, there's nothing that LXCFS can do about it.

You need your container manager to support system call interception to return an altered sysinfo response. Incus supports that but I don't believe Docker, Podman or any of the application container runtimes do.
