### ISSUE TITLE
How should we report available swap?

### ISSUE THREAD

**Issue by hallyn** [lxc/lxcfs#68]
Perhaps this should be discussed on the mailing list, or merged with another issue.  But let's start here.

The problem: cgroup.memory.memsw.limit_in_bytes is combined available memory and swap.  lxcfs's meminfo currently reports 'swap available' as memsw.limit_in_bytes - memory.limit_in_bytes.  In the case where those two are the same, meminfo will report 0 swap available, and up to memsw.limit_in_bytes for swap usage.

What is the best way to handle this?

Continue as now.

We could simply not report Swap Available and instead report a lxcfs-specific value.

We could make the memory and swap available numbers dynamic.  That's going to be confusing for a lot of legacy software.

Other ideas?

**Comment by stgraber** [comment]
I think making things dynamic shouldn't be confusing to tools, so long as we do:
 - Memory total = memory.limit - (memsw.limit - memory.limit)
 - Memory used = memory.usage - (memsw.usage - memory.usage)
 - Swap total = max(memsw.limit - memory.limit, memsw.usage - memory.usage)
 - Swap used = memsw.usage - memory.usage

Yes, when memsw.limit == memory.limit, any used swap will be seen as a decrease in total memory and an increase of swap, that may look a bit confusing but since memory hotplug/hotremove is a thing, I don't expect it to confuse userspace in any way that the kernel doesn't already do. The total memory will remain constant which is what's important for any userspace software trying to figure out how much it can use.

**Comment by hallyn** [comment]
Using the above equations, if memlimit = 100 and memswlimit = 300, then we'd report 

memlimit - (memswlimit - memlimit) = 100 - (300 - 100) = -100

I think so long as we stick with the idea that these are dynamic, it's ok to report

memlimit = 100
swaplimit = 200

and in the case of memlimit = memswlimit = 100 to report

memlimit = 100
swaplimit = 0

The used limit formulas would look something like what you have.

**Comment by hallyn** [comment]
so the one case where memtotal should be reported as < memory.limit is if we have swap usage taking up a chunk of the (memsw.limit - mem.limit).

For instance,

memsw.limit = mem.limit = 100

swapusage = 5

mem.limit is now 95 bc the 5 cannot be accounted to swap only.

**Comment by hallyn** [comment]
So something like:

```
        final_memlimit = memlimit;
        final_swaplimit = memswlimit;
        if (memswlimit != 0) {
                swaponly = memswlimit - memlimit;
                if (memswusage > swaponly)
                        final_memlimit -= (memswusage - swaponly);
                final_swaplimit = memswlimit - final_memlimit;
        }
```

**Comment by hallyn** [comment]
Then again maybe the total mem vs swap is not worth worrying about.  It is not the guest's concern that it *can* get swapped out.  The guest just needs to know how much memory+swap it can consume.

So stick with MemTotal = memory.limit_in_bytes and SwapTotal = memory.memsw.limit_in_bytes - MemTotal.

**Comment by hallyn** [comment]
As people use what we have with real applications maybe some obviously useful changes will come up, but I'm going to close this for now.
