### ISSUE TITLE
Support for /sys/devices/system/cpu

### ISSUE THREAD

**Issue by tssge** [lxc/lxcfs#88]
Support for /sys/devices/system/cpu so that the LXC system does not see the additional CPUs available for host.

Current behavior causes bugs with CPU count autodetection on programs like nginx and others which try to generate their process count based on the CPUs available on system. They will use host's value which is wrong.

Example of current, non working, /sys/devices/system/cpu:

```
root@fr-gcp4:/sys/devices/system/cpu# ls
cpu0   cpu12  cpu16  cpu2   cpu23  cpu27  cpu30  cpu6  cpuidle       microcode  possible
cpu1   cpu13  cpu17  cpu20  cpu24  cpu28  cpu31  cpu7  intel_pstate  modalias   power
cpu10  cpu14  cpu18  cpu21  cpu25  cpu29  cpu4   cpu8  isolated      offline    present
cpu11  cpu15  cpu19  cpu22  cpu26  cpu3   cpu5   cpu9  kernel_max    online     uevent
```

Example of how it should work:

```
root@fr-gcp4:/sys/devices/system/cpu# ls
cpu0   cpu1  cpu2  cpu3   cpu4  cpu5 cpuidle       microcode  possible ntel_pstate  modalias 
power isolated      offline    present kernel_max    online     uevent
```

**Comment by jdrews** [comment]
ACK 
I'd like to see this as well.

**Comment by tssge** [comment]
This bug will cause dedicated server software of a game called Rust to eat up all CPU inside an LXC container. The only fix is to remove any cpu limits or fix this bug.

**Comment by jdrews** [comment]
Agreed. I'd fully expect other software to implement multithreaded scaling techniques based on the amount of processors seen. If we limit the number of processors seen we can control these scaling techniques and distribute load across all containers evenly.

**Comment by hallyn** [comment]
I may code this up after 16.10 release as a 3.0 feature.

**Comment by hallyn** [comment]
I don't know when I'll have time to devote to this so I encourage anyone
interested to go ahead and start.

The basics shouldn't be complicated - create a new 'sys' directory in
lxcfs next to proc and cgroup, give it a 'cpu' subdirectory which is to be
bind-mounted under /sys/devices/system/cpu, then virtualize cpu%d under
that.  The only complication is how to pass requests on to the host's
/sys/devices/system/cpu/$name for other files/dirs.

**Comment by Blub** [comment]
Care must be taken with respect to what numbers are shown there.
If it is implemented to count from 0 up it can create a discrepancy between what you see in `/sys/devices/system/cpu` and the cpu IDs you're assigned to eg. via the `cpuset` cgroup and also via `sched_getaffinity(2)` and what is expected in a call to `sched_setaffinity(2)`. So you might have to name the CPU directories after their real IDs, but then people will still complain about exposing host information if you see CPUs 40 to 47 as 40..47 instead of 0..7 - not really an issue for me personally, though, just something to keep in mind.

At least if the `online` file is available scripts using `getconf(1)` and programs using `sysconf(3)` will spawn the right number of workers, so at least the practical problems will be fixed this way.

But this is only the case for programs pinned to cores. Often one just wants to limit the load instead without pinning to cores, which still has no practical solution AFAIK?

**Comment by dlasher** [comment]
+1 - All-in-one solutions like proxmox, recently having moved from OpenVZ to LXC, need this.

**Comment by virtualtam** [comment]
Hi!
Related Proxmox discussions:
- in-depth [Proxmox bug 839](https://bugzilla.proxmox.com/show_bug.cgi?id=839) - LXC containers show host /proc limits instead of actual limits available 
- [Forum thread](https://forum.proxmox.com/threads/lxc-container-show-load-and-hardware-from-host.26051/) - LXC Container show Load and hardware from Host

**Comment by azizarnold** [comment]
yes please we need this. I use proxmox too which uses LXC and cpu core counts are confusing clients. May even cause issues with purchasing software that costs per core assigned to it.

**Comment by TheNuclearCat** [comment]
Any updates on this?

**Comment by hallyn** [comment]
No updates yet.  Still considering it, have not yet found time to start.

**Comment by BrickXu** [comment]
JVM that works in LXC need this PR to make `Runtime.getRuntime.availableProcessors()` return the correct core numbers.

**Comment by hallyn** [comment]
Seems like JVM could be fixed to use /proc/cpuinfo.

**Comment by BrickXu** [comment]
@hallyn thanks for your reply, now only JDK9 could detected cpuset and return the correct cores, for JDK8/7 they could not work with cpuset or something else in the cgroup.

**Comment by kulong0105** [comment]
have any planning for this feature?
